# Generated by Django 2.0.6 on 2018-06-10 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Futugo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yakubun', models.CharField(max_length=200, verbose_name='訳文')),
            ],
        ),
        migrations.CreateModel(
            name='Kansaikotoba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kotoba', models.CharField(db_index=True, max_length=50, verbose_name='関西語')),
                ('is_has_kanji', models.BooleanField(default=False, verbose_name='漢字あるか')),
                ('kanji', models.CharField(db_index=True, max_length=50, verbose_name='漢字')),
            ],
            options={
                'verbose_name': '関西語表',
                'verbose_name_plural': '関西語表',
                'ordering': ('kotoba',),
            },
        ),
        migrations.AddField(
            model_name='futugo',
            name='ori_kotoba',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='futugo', to='converter.Kansaikotoba'),
        ),
    ]
