# Generated by Django 2.0.6 on 2018-06-10 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='futugo',
            options={'verbose_name': '普通語表', 'verbose_name_plural': '普通語表'},
        ),
    ]
