# Generated by Django 2.0.6 on 2018-06-10 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0004_kansaikotoba_futu_p'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kansaikotoba',
            old_name='futu_p',
            new_name='futu_id',
        ),
    ]
