# Generated by Django 2.0.6 on 2018-07-14 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0006_remove_kansaikotoba_futu_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='kansaikotoba',
            name='example',
            field=models.TextField(blank=True, max_length=250, verbose_name='例'),
        ),
    ]
