# Generated by Django 2.0.6 on 2018-07-14 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0007_kansaikotoba_example'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kansaikotoba',
            name='example',
        ),
        migrations.AddField(
            model_name='futugo',
            name='example',
            field=models.TextField(blank=True, max_length=250, verbose_name='例文'),
        ),
    ]
